name: rearch_example
description: Rearch example application making use of warm up capsules.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rearch: ^1.6.1
  rearch: ^1.8.0+0
  shared_preferences: ^2.2.0
  go_router: ^14.0.2

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

